添加方法集的读取及实现
gotomicro/egen pull request #15
Opened 2022-09-27 12:57 UTC by jackj-ohn1

2022-09-28 02:31 UTC, flycash reviewed
嘿嘿，你接着做，我觉得你这个那么粗暴，后面估计一堆坑。踩了再说

2022-09-28 02:31 UTC, flycash commented on cmd/egen/dao/exec.go
> +
你这是不是又换了换行符？可以在 GoLand 的设置里面适用固定的换行符

2022-09-28 02:31 UTC, flycash commented on internal/model/ast/ast_test.go
> +	Hello(name string) (int64, error)
我觉得你可能会需要进一步解析返回值，比如说返回的是单个 Order，或者 Order 切片，或者你这种直接就是一个值

2022-09-28 02:31 UTC, flycash commented on internal/model/ast/convert.go
> +		if len(one.Methods) <= 0 {
这个判断方式有点离谱呀。不如在 type 里面标记一下是结构体还是接口？如果是接口就说明需要给它提供实现

2022-09-30 06:28 UTC, jackj-ohn1 commented on internal/model/ast/convert.go
> +		if len(one.Methods) <= 0 {
为了生成在同一个文件里面 感觉只能这样合并

2022-10-11 03:59 UTC, flycash requested changes

2022-10-11 03:59 UTC, flycash commented on cmd/egen/dao/exec.go
> +			v.Methods[k].FuncName = strings.Replace(v.Methods[k].FuncName, v.GoName, v.PkgName+v.GoName, -1)
不要这么写。 model 本身应该是一个和你代码生成没有关系的东西，所以 Model 的数据你应该是只读的。如果你希望修改，那么你应该定义出来另外一个结构体，将 model 的数据复制过去

2022-10-11 03:59 UTC, flycash commented on cmd/egen/dao/exec.go
> +				v.Methods[k].Results[i] = strings.Replace(v.Methods[k].Results[i], v.GoName, v.PkgName+v.GoName, -1)
同样的道理，这里你也不要去修改

2022-10-11 03:59 UTC, flycash commented on cmd/egen/dao/exec.go
> +				v.Methods[k].Results[i] = strings.Replace(v.Methods[k].Results[i], v.GoName, v.PkgName+v.GoName, -1)
相当于 AST 转 Model 再转你代码生成要用的数据。比如说：
```go
type GenModel struct {
    Model
}

type GenMethod struct {
     Method
    FuncName string
}
```

2022-10-11 03:59 UTC, flycash commented on internal/model/ast/ast.go
> +	switch node.(type) {
switch n := node.(type) 这个 n 就是类型断言之后的结果，你就不再需要 `fd:=node.(*ast.Field)`

2022-10-11 03:59 UTC, flycash commented on internal/model/ast/ast_test.go
> +								FuncName: "Hello(name []string) (int64, error)",
你这个 FuncName 解析出来不应该是 Hello 吗？毕竟你都有 Result 和 Parameter 了

2022-10-11 03:59 UTC, flycash commented on internal/model/ast/convert.go
> +			if models[i].GoName+"DAO" == one.GoName {
所以你这是为了合并？

2022-10-11 03:59 UTC, flycash commented on cmd/egen/dao/exec.go
> +				v.Methods[k].Results[i] = strings.Replace(v.Methods[k].Results[i], v.GoName, v.PkgName+v.GoName, -1)
我觉得应该是，根据你后面的代码，这部分应该定义成：
```go
type GenModel struct {
    entity Model
    dao Model
}

type GenMethod struct {
     Method
    FuncName string
}
```
也就是说，你通过一个新的结构体将 User 和 UserDAO 的模型信息封装在一起。当然，你也可以定义成别的样子。不过核心就是 Model 永远代表的就是一个和其它步骤没有关系的类型信息

2022-10-11 11:33 UTC, jackj-ohn1 commented on internal/model/ast/ast_test.go
> +								FuncName: "Hello(name []string) (int64, error)",
funcName是func hello(name string) int 这样的一个字符串 在模板里拼接有点麻烦就直接外面拼了

2022-10-11 11:33 UTC, jackj-ohn1 commented on internal/model/ast/convert.go
> +			if models[i].GoName+"DAO" == one.GoName {
是的 我感觉这样写好low

2022-10-19 06:49 UTC, flycash requested changes
- 整理测试用例。把 first, genDAO, second 和 third 这几个文件夹改名，改成对应的测试用例的名字，不然根本看不懂。
- 你把 genDAO/data.go 放在 integration/dao 下面
- 增加测试用例：各种手写 SQL 的样子，IN和非 IN 都要，增删改查也要考虑

2022-10-26 07:04 UTC, flycash reviewed
你需要修改的：
- 所有的留言都看一遍，改完了的点一下 resolve
- 把 interface 的模板拆出来，不要在一个方法的模板里面同时处理删改查
- 在 SELECT 语句里面，如果用户指定的 SELECT *，那么就直接走过去我们的 NewOne 之类的来构造；如果用户指定了列，因为我们目前只是考虑了指定单一的一个列，那么就额外再搞出来一个类似 New 的方法，里面会把这个列的值，转成对应的类型，例如 int, string 之类的。本质上就是在模板里面，代码要清晰，要简单，因为模板是很难读懂的

2022-10-26 07:04 UTC, flycash commented on internal/generate/mysql_template/interface.gohtml
> +func (dao *{{- $name}}GenDAO) {{.QuotedFunc}} {
不要在一个方法里面写得那么复杂，因为很明显，我们可以考虑说按照 select, update, delete 来拆开不同模板。主要还是在你里面的一堆 if-else 已经导致整个模板基本上读不懂了

2022-10-26 07:04 UTC, flycash commented on cmd/egen/dao/exec.go
> +			v.SelfPkgName = "code"
这又是什么神奇的地方？code 是指啥？

2022-10-26 07:04 UTC, flycash commented on internal/generate/mysql_template/interface.gohtml
> +	Sql := "{{- $model.QuotedColOfSql $content}}"
小写的 sql

2022-10-26 07:04 UTC, flycash commented on internal/generate/mysql_template/interface.gohtml
> +	{{- if eq (index $t 0) "more"}}
more 又是啥？

2022-10-26 07:04 UTC, flycash commented on internal/generate/mysql_template/interface.gohtml
> +	{{- else if eq (index $t 0) "less"}}
less 又是啥？

2022-10-26 07:06 UTC, flycash commented
把 deepsource 和 format go 的修复了

2022-10-26 07:09 UTC, flycash commented
代码测试覆盖率提升上去

2022-10-26 08:11 UTC, jackj-ohn1 commented on internal/generate/mysql_template/interface.gohtml
> +	Sql := "{{- $model.QuotedColOfSql $content}}"
与包重名

2022-10-26 08:12 UTC, jackj-ohn1 commented on internal/generate/mysql_template/interface.gohtml
> +	{{- if eq (index $t 0) "more"}}
如果是#ids 就是个切片，#status是单个参数 为了区别这两种，主要是为了后面的append

2022-10-26 08:51 UTC, flycash commented on internal/integration/test_custom_sql/data.go
> +	UpdateOne(ctx context.Context, status bool) (int64, error)
Update 你还需要额外的测试用例：
```go
	// @update UPDATE `user_dao` SET `username`=#username WHERE `status`=#status
	UpdateUserName(ctx context.Context, username string, status bool) (int64, error)
```

2022-11-07 02:01 UTC, merged