新增insert模板
gotomicro/egen pull request #4
Opened 2022-07-14 14:01 UTC by jackj-ohn1

2022-07-15 06:53 UTC, flycash requested changes

2022-07-15 06:53 UTC, flycash commented on internal/generate/mysql.go
> +func (dao *{{$actual}})Insert(users... *User)(int64,error){
这里不应该出现User 这个东西，你需要能够操作任意类型

2022-07-15 06:53 UTC, flycash commented on internal/generate/mysql.go
> +{{- $col = print $col ")"}}
这里定义了太多全局的变量，使得你的模板很难理解

2022-07-15 06:53 UTC, flycash commented on internal/generate/mysql.go
> +type {{$actual}} struct{
可以在 Model 里面加一个字段，比如说叫做 Name:
```go
type Model struct {
    Name string
}
```
在 User 里面，这个 Name = "User", 在 Order 的时候，Name = "Order"。
所以这里你可以改成:
```
type {{.Name}}DAO struct {
    DB *sql.DB
}
```

2022-07-15 06:53 UTC, flycash commented on internal/generate/mysql_test.go
> +	testCase := ReCode{
在这里再加一个 Order 的测试用例

2022-07-15 06:53 UTC, flycash commented on internal/generate/mysql.go
> +{{- end}}
类似这种循环，你不应该放在全局的，因为它只被 INSERT 语句使用到了。所以你应该在 INSERT 语句里面拼接

2022-07-15 06:53 UTC, flycash commented on internal/generate/mysql_test.go
> +			ActTableName: "UserName",
不要叫做 ActTableName，叫做 Name 或者 GoName 都可以

2022-07-15 06:53 UTC, flycash commented on internal/generate/mysql_test.go
> +type ReCode struct {
定义为局部匿名结构体，直接在测试里面定义。不需要在这里定义，而且 ReCode 这个名字也不太清晰，看不出来是啥

2022-07-15 06:53 UTC, flycash commented on internal/generate/mysql_test.go
> +type UserName struct {
改名叫做 User，UserName 看起来是一个字段。而且顶天了 UserName 里面也应该是 FirstName 和 LastName MiddleName 之类的，为什么你这里会有一个 LoginTime 字段

2022-07-15 06:53 UTC, flycash commented on internal/generate/mysql_test.go
> +	var agrs = make([]interface,len(users)*(2+1))
为什么要额外 + 1？

2022-07-15 06:53 UTC, flycash commented on internal/generate/mysql_test.go
> +				{ColName: "hello_world", IsPrimaryKey: true, ActColName: "HelloWorld"},
你的结构体里面都没有 hello_world 这个东西，这是哪来的？

2022-07-15 06:53 UTC, flycash commented on internal/generate/mysql_test.go
> +	sqlSen := "INSERT INTO 'user_name'('login_time','first_name','hello_world') VALUES" + str
在 MySQL 里面，引号用的是反引号 `，而不是单引号。

2022-07-15 06:53 UTC, flycash commented on internal/generate/mysql_test.go
> +	sqlSen := "INSERT INTO 'user_name'('login_time','first_name','hello_world') VALUES" + str
如果因为字符串是用 ` 括起来，导致你这里不能使用 `，那么你可以把这个 wantCode 挪出去作为一个文件，在这个目录下创建一个 testdata 目录。然后你测试的时候就从这个目录下面读文件

2022-07-15 06:53 UTC, flycash commented on internal/model/types.go
> +	Tag          string
你应该不需要这个字段

2022-07-15 06:53 UTC, flycash commented on internal/model/types.go
> +	ActColName   string
改成 Name 或者 GoName

2022-07-15 06:53 UTC, flycash commented on internal/model/types.go
> +	ActTableName string
改成 Name 或者 GoName

2022-07-15 13:09 UTC, flycash requested changes

2022-07-15 13:09 UTC, flycash commented on internal/generate/testdata/data.txt
> +type UserName struct{
我就觉得离谱，为何还是 UserName？ DAO 去哪里了？

2022-07-15 13:09 UTC, flycash commented on internal/generate/mysql.go
> +{{- $actual := .GoName}}
actual 真的是一个很差的名字，什么都看不出来。中文意思是”真的“，真的什么？变量名字不可能是形容词的，只能是名词

2022-07-15 13:09 UTC, flycash commented on internal/generate/mysql_test.go
> +			Tag:       "`",
Model 肯定不需要这个 Tag 的。具体的分隔符不是 Model 控制的，是你的实现控制的，比如说你是 MySQL 所以你应该用 ` 作为 separator。你把这个写在 Model 里面，万一我要生成 SQLite 的代码呢？我要生成 Oracle 的代码呢？

2022-07-15 13:31 UTC, flycash requested changes

2022-07-15 13:31 UTC, flycash commented on internal/generate/mysql_test.go
> +	HelloWorld string
虽然是测试数据，但是也稍微设计好一点……你随便从网上抄一个 User 表设计，这个 UserName 实在没啥意义。UserName 里面放 LoginTime 和 FirstName，再一个 HelloWorld 我感觉有点受不了

2022-07-15 13:31 UTC, flycash commented on internal/generate/mysql_test.go
> +			Tag:       "`",
我懂了，这个是我误会了，因为要定义方法在 Model 上只能在这里定义

2022-07-15 14:19 UTC, flycash requested changes
你把全部和主键有关的代码删掉，主键问题需要进一步考虑的，后面再说。现在你就是无脑把所有的列都插入进去。
另外，把所有和 INSERT 没有关系的代码都删掉。

2022-07-15 14:19 UTC, flycash commented on internal/model/types.go
> +	ActColName   string
改为 GoName

2022-07-15 14:19 UTC, flycash commented on internal/generate/mysql.go
> +type Name struct {
这个放到测试文件里面

2022-07-15 14:19 UTC, flycash commented on internal/generate/mysql.go
> +	tSelect := template.New("update")
改个名字，叫做 mysql

2022-07-15 14:19 UTC, flycash commented on internal/generate/mysql.go
> +{{- $field := .GoName}}
这个没必要赋值给 $field，你可以直接在代码里面用，因为不存在作用域之类的问题

2022-07-15 14:19 UTC, flycash commented on internal/generate/mysql.go
> +func (dao *{{$field}}DAO)Update(users ...*{{$field}})(int64,error){
把 users 改成 vals

2022-07-15 14:19 UTC, flycash commented on internal/model/types.go
> +func (m *Model) ReturnFieldName(primary, all bool) string {
拆成两个方法，一个是返回你的 PK 的，一个是返回全部的

2022-07-15 14:19 UTC, flycash commented on internal/model/types.go
> +func (m *Model) ReturnQuestionMark(lengthStr string, query bool) string {
同样拆成两个。我觉得你应该不需要 =？ 的这个，那都是到 update 的时候才会考虑

2022-07-15 14:19 UTC, flycash commented on internal/model/types.go
> +func (m *Model) ReturnColNum(primary, all bool) string {
拆成两个

2022-07-15 14:19 UTC, flycash commented on internal/model/types.go
> +func (m *Model) ReturnWhereInfor(primary bool) string {
你把所有和 INSERT 没有关系的代码删掉，全部检查一下

2022-07-15 14:19 UTC, flycash commented on internal/model/types.go
> +func (m *Model) InsertReplaceParameter() string {
暂时你不用考虑主键非主键的问题，你全部都插入

2022-07-16 08:52 UTC, jackj-ohn1 commented on internal/generate/mysql_test.go
> +	testCase := ReCode{
done

2022-07-16 08:52 UTC, jackj-ohn1 commented on internal/model/types.go
> +	ActColName   string
done

2022-07-16 08:52 UTC, jackj-ohn1 commented on internal/model/types.go
> +	ActTableName string
done

2022-07-16 08:52 UTC, jackj-ohn1 commented on internal/generate/testdata/data.txt
> +type UserName struct{
done

2022-07-16 08:52 UTC, jackj-ohn1 commented on internal/generate/mysql.go
> +{{- $actual := .GoName}}
done

2022-07-16 08:53 UTC, jackj-ohn1 commented on internal/generate/mysql.go
> +type Name struct {
done

2022-07-16 08:53 UTC, jackj-ohn1 commented on internal/generate/mysql.go
> +{{- $field := .GoName}}
done

2022-07-16 08:54 UTC, jackj-ohn1 commented on internal/generate/mysql.go
> +func (dao *{{$field}}DAO)Update(users ...*{{$field}})(int64,error){
done

2022-07-16 08:54 UTC, jackj-ohn1 commented on internal/model/types.go
> +func (m *Model) ReturnFieldName(primary, all bool) string {
done

2022-07-16 08:54 UTC, jackj-ohn1 commented on internal/model/types.go
> +func (m *Model) ReturnColNum(primary, all bool) string {
done

2022-07-16 08:54 UTC, jackj-ohn1 commented on internal/model/types.go
> +func (m *Model) InsertReplaceParameter() string {
done

2022-07-16 08:59 UTC, jackj-ohn1 commented on internal/generate/mysql_test.go
> +type ReCode struct {
done

2022-07-16 08:59 UTC, jackj-ohn1 commented on internal/generate/mysql_test.go
> +type UserName struct {
done

2022-07-16 08:59 UTC, jackj-ohn1 commented on internal/generate/mysql_test.go
> +	HelloWorld string
done

2022-07-16 09:00 UTC, jackj-ohn1 commented on internal/model/types.go
> +func (m *Model) ReturnQuestionMark(lengthStr string, query bool) string {
我直接删了现在insert不需要 后面再写

2022-07-16 09:01 UTC, jackj-ohn1 commented on internal/model/types.go
> +func (m *Model) ReturnWhereInfor(primary bool) string {
done

2022-07-16 11:30 UTC, flycash requested changes

2022-07-16 11:30 UTC, flycash commented on internal/generate/mysql.go
> +	if err != nil {
不要打印 error，直接返回 error

2022-07-16 11:30 UTC, flycash commented on internal/generate/mysql.go
> +	tSelect := template.New("mysql")
这个 tSelect 显然也不准确，换一个

2022-07-16 11:30 UTC, flycash commented on internal/generate/mysql.go
> +	tSelect = template.Must(tSelect.Parse(`
这里不需要再一次 Must 吧？

2022-07-16 11:30 UTC, flycash commented on internal/generate/mysql_test.go
> +type UserName struct {
你这里还是叫做 UserName 呀？我是说改名叫做 User

2022-07-16 11:30 UTC, flycash commented on internal/model/types.go
> +func (m *Model) ReturnTableName() string {
叫做 QuotedTableName

2022-07-16 11:30 UTC, flycash commented on internal/model/types.go
> +func (m *Model) ReturnAllCol() string {
这些方法不要加 Return 前缀，你检查一下

2022-07-17 06:10 UTC, flycash requested changes
我真是无法理解，为什么做一个 INSERT，一会是 UPDATE，一会是 SELECT，说好的 INSERT 呢？

2022-07-17 06:10 UTC, flycash commented on internal/generate/mysql.go
> +	sqlSen := "SELECT {{.QuotedOrderedCol}} FROM {{.QuotedTableName}} WHERE {{.QuotedColWithQuestionMark .QuotedOrderedColWithWhere}}"
离谱，我的 INSERT 哪里去了？

2022-07-17 06:10 UTC, flycash commented on internal/generate/mysql_test.go
> +type User struct {
把对应的 testdata 里的 user_name.txt 改成 user.txt

2022-07-17 06:10 UTC, flycash commented on internal/generate/mysql_test.go
> +			log.Print(w.String())
在测试里面也不要打印数据，要使用断言。因为正常情况下，我们不会希望说手动去检查数据对还是不对

2022-07-17 06:10 UTC, flycash commented on internal/generate/testdata/order.txt
> +	numAff,err := re.RowsAffected()
可以直接改成 `return re.RowsAffected`

2022-07-17 06:10 UTC, flycash commented on internal/generate/testdata/order.txt
> +	numAff,err := re.RowsAffected()
测试数据和对应的模板都直接返回

2022-07-18 09:52 UTC, flycash requested changes

2022-07-18 09:52 UTC, flycash commented on internal/generate/mysql.go
> +	"html/template"
这里使用 text/template。`html/template` 和 `text/template` 的区别是， `html/template` 会对 HTML 里面的特殊语法进行转义，一般是在 WEB 框架才会考虑使用。我们这里用纯粹的 `text/template` 比较合适

2022-07-18 09:52 UTC, flycash commented on internal/generate/mysql.go
> +	var agrs = make([]interface,len(vals)*({{print (len .Fields)}}))
这样写可以吗？
```
var agrs = make([]interface,len(vals)*{{len .Fields}})
```

2022-07-18 09:52 UTC, flycash commented on internal/generate/mysql_test.go
> +	testCases := []struct {
在 testCases 里面加一个字段 
```
testdata string
```
然后 testdata 在 user 下是 `user.txt` 而在 order 下是 `order.txt`。
因为在单元测试里面，这种数据是可以在具体的测试用例里面弄好的，就不要在整个测试方法里面定义。

2022-07-18 09:52 UTC, flycash commented on internal/generate/mysql_test.go
> +			//log.Println(w.String())
删掉

2022-07-18 09:52 UTC, flycash commented on internal/generate/mysql.go
> +{{- $separator := .Tag}}
这个你后面已经没有用到了，所以可以删掉了 separator 了

2022-07-18 09:52 UTC, flycash commented on internal/generate/mysql.go
> +	re,err := dao.DB.Exec(sqlSen,args)
把 re 改名叫做 res。在缩写上我们一般用 res 来代表 result，或者ret 来代表 return。我一般用 res，有些人喜欢用 ret，这个都可以

2022-07-18 09:52 UTC, flycash commented on internal/model/types.go
> +func (m *Model) QuotedExecArgsWithPK() string {
这个方法你应该是咩有用到，所以可以删掉它

2022-07-18 09:52 UTC, flycash commented on internal/model/types.go
> +func (*Model) InsertWithReplaceParameter(col string) string {
这个方法看上去其实有点奇怪。因为本身`col` 是你自己主动拼接到的，然后在内部你又重新按照 `,` 来切割了。所以实际上这里没有必要传入这个`col`参数，直接使用全部字段就可以了。后面 len(colSlice) 直接改成 len(Fields)。
即便是后面我们考虑忽略主键的问题，我们可以有额外的方法或者字段来控制

2022-07-18 09:52 UTC, flycash commented on internal/model/types.go
> +func (m *Model) QuotedExecArgsWithAll() string {
这个你也应该是没有用到吧？

2022-07-18 09:52 UTC, flycash commented on internal/model/types.go
> +func (m *Model) QuotedExecArgsWithData(owner, col string) string {
可以把 WithData 这个后缀删掉。因为 WithData 给人的感觉是你处理了值，实际上你只是拼凑了一下字段而已。

2022-07-18 09:52 UTC, flycash commented on internal/model/types.go
> +		if strings.Contains(col, v.ColName) {
目前来讲你没有必要做这种判断，直接把全部列都罗列出来。主键的问题后面考虑，因为这种 Contains 的判断方式，只有我们这种很了解模板的人才能理解，一般人刚看到是看不明白这里为什么要有一个判断的。

2022-07-18 09:52 UTC, flycash commented on internal/model/types.go
> +func (m *Model) QuotedPrimaryKeyCol() string {
这个方法应该没有用到，可以删掉

2022-07-18 09:52 UTC, flycash commented on internal/model/types.go
> +func (m *Model) QuotedPrimaryKeyColWithNum() string {
这个方法应该也没有用到，也可以删掉

2022-07-18 11:52 UTC, jackj-ohn1 commented on internal/model/types.go
> +func (m *Model) QuotedPrimaryKeyColWithNum() string {
done

2022-07-18 11:52 UTC, jackj-ohn1 commented on internal/model/types.go
> +func (m *Model) QuotedPrimaryKeyCol() string {
done

2022-07-18 11:52 UTC, jackj-ohn1 commented on internal/model/types.go
> +		if strings.Contains(col, v.ColName) {
done

2022-07-18 11:53 UTC, jackj-ohn1 commented on internal/model/types.go
> +func (m *Model) QuotedExecArgsWithData(owner, col string) string {
done

2022-07-18 11:53 UTC, jackj-ohn1 commented on internal/generate/mysql.go
> +{{- $separator := .Tag}}
done

2022-07-18 11:53 UTC, jackj-ohn1 commented on internal/generate/mysql_test.go
> +			//log.Println(w.String())
done

2022-07-18 11:53 UTC, jackj-ohn1 commented on internal/generate/mysql_test.go
> +	testCases := []struct {
done

2022-07-18 11:53 UTC, jackj-ohn1 commented on internal/generate/mysql.go
> +	var agrs = make([]interface,len(vals)*({{print (len .Fields)}}))
done

2022-07-18 11:53 UTC, jackj-ohn1 commented on internal/generate/mysql.go
> +	"html/template"
done

2022-07-19 11:30 UTC, flycash requested changes

2022-07-19 11:30 UTC, flycash commented on .CHANGELOG.md
> +- [internal/generate:添加crud的template模板](https://github.com/gotomicro/egen/pull/4)
改成添加 insert 模板

2022-07-19 13:49 UTC, merged