新增select模板并将模板细分成单个文件
gotomicro/egen pull request #5
Opened 2022-07-21 08:09 UTC by jackj-ohn1

rebase到origin/main

internal/generate/mysql_template:新增模板文件  ~/mysql.go: 修改模板的渲染操作

新增select模板

2022-07-21 13:03 UTC, flycash requested changes
你把测试数据的 txt 后缀都改为 go。也就是做成 Go 文件，这样你就能直接看出来自己生成的代码是不对的

2022-07-21 13:03 UTC, flycash commented on internal/generate/mysql_template/insert.go.tpl
> +	res,err := dao.DB.ExecContext(ctx,sqlSen,args)
args 记得三个点

2022-07-21 13:03 UTC, flycash commented on internal/generate/mysql_template/select.go.tpl
> +	row,err := dao.DB.QueryRowContext(ctx,query,args)
args 三个点。其它你都检查一下

2022-07-21 13:03 UTC, flycash commented on internal/generate/mysql_template/select.go.tpl
> +func (dao *{{.GoName}}DAO) SelectBatchRow(ctx context.Context,query string,args ...any) (*[]{{.GoName}},error) {
返回值不对

2022-07-21 13:03 UTC, flycash commented on internal/generate/mysql_template/select.go.tpl
> +func (dao *{{.GoName}}DAO) NewBatch(rows *sql.Rows) (*[]{{.GoName}},error) {
返回值不对

2022-07-21 13:03 UTC, flycash commented on internal/generate/mysql_template/select.go.tpl
> +func (dao *{{.GoName}}DAO) SelectByWhere(ctx context.Context,where string,args ...any) {
返回值不对

2022-07-21 13:03 UTC, flycash commented on internal/generate/mysql_template/select.go.tpl
> +	s := "SELECT * FROM {{.QuotedTableName}} WHERE " + where
不要使用 SELECT * 。一般来说我们都显示指定所有的列。一者是性能比较好，另外一方面也是因为 * 后面加了列或者调整了列的顺序都会导致代码崩溃。

2022-07-21 13:03 UTC, flycash commented on internal/generate/mysql_template/insert.go.tpl
> +type {{.GoName}}DAO struct {
在前面加上一个 import。因为这里你需要 import sql 这个包

2022-07-22 12:54 UTC, flycash requested changes

2022-07-22 12:54 UTC, flycash commented on internal/generate/mysql_template/select.go.tpl
> +func (dao *{{.GoName}}DAO) SelectByRow(ctx context.Context, query string, args ...any) (*{{.GoName}}, error) {
SelectByRow => SelectByRaw
Raw 在这个语境下是指原生查询。在ORM 语境下就是指用户直接写 SQL。
后面 ByRow 应该都是写错了，应该是 ByRaw

2022-07-22 12:54 UTC, flycash commented on internal/generate/mysql_template/select.go.tpl
> +func (dao *{{.GoName}}DAO) SelectBatchRow(ctx context.Context, query string, args ...any) ([]*{{.GoName}}, error) {
前面都有 By, 这个也加上 By

2022-07-22 12:54 UTC, flycash commented on internal/generate/testdata/user.go
> +	return vals, rows.Err()
sql.Rows 有 Err 方法吗？

2022-07-22 12:54 UTC, flycash commented on internal/model/types_test.go
> +var m = &Model{
测试里面不要使用这种包变量。你可以在每个测试里面单独声明，也可以创建一个方法，每次都返回这个。

一个良好的测试要满足：
- 独立性：即测试互相之间应该没有影响，也没有数据依赖。包变量就违背了这条约束
- 自动化：即你的测试是可以用 CI 工具跑，可以跑任意多次而不需要人手工处理的
- 可重复性：如果代码不发生修改，那么每次执行结果都是确定的

2022-07-22 12:54 UTC, flycash commented on internal/model/types_test.go
> +var m = &Model{
设计单元测试要考虑：
- 边界值：例如对数字来说是 0，最大值，最小值；对指针来说是 nil，对数组或者切片来说，nil，空数组...
- 异常分支：即返回 error 的分支。但是有些时候一些 error 分支是比较难测试的，这种可以考虑忽略

2022-07-22 12:54 UTC, flycash commented on internal/model/types.go
> +func (m *Model) QuotedExecArgsWithParameter(flag, owner, col string) string {
取地址符号固定是 &，所以你可以删除 flag 参数

2022-07-22 13:04 UTC, jackj-ohn1 commented on internal/generate/testdata/user.go
> +	return vals, rows.Err()
有的

2022-07-24 07:48 UTC, flycash requested changes

2022-07-24 07:48 UTC, flycash commented on internal/generate/testdata/user.go
> +func (dao *UserDAO) NewOne(row *sql.Row) (*User, error) {
NewOne 和 NewBatch 都应该进来就要先检测 Err。如果有 Err，那么就直接返回，不需要 Scan 了。站在用户的角度，它肯定不希望说他调用 New* 方法之前还得自己先检测 Err

2022-07-24 07:49 UTC, flycash requested changes

2022-07-24 07:49 UTC, flycash commented on internal/model/types.go
> +func InitModel() *Model {
这个应该放在测试文件里面。因为它只能被用于测试。只有测试用的类型，接口，方法，都定义在测试文件里面

2022-07-24 07:51 UTC, jackj-ohn1 commented on internal/model/types.go
> +func InitModel() *Model {
好的

2022-07-24 07:51 UTC, jackj-ohn1 commented on internal/generate/testdata/user.go
> +func (dao *UserDAO) NewOne(row *sql.Row) (*User, error) {
ok

2022-07-25 02:41 UTC, flycash requested changes

2022-07-25 02:41 UTC, flycash commented on internal/generate/testdata/order.go
> +	var vals = make([]*Order, 0)
这边指定容量的时候不要指定0. 指定 0 意味着插入一个元素就要扩容。我觉得一般按照批次来算，比较多的人是十个一批，二十个一批，或者五十个一批，你挑一个就好了。

预估容量的时候，过大浪费空间，过小则是引起扩容，加大内存分配的压力和 GC 的压力

2022-07-25 02:41 UTC, flycash commented on internal/generate/testdata/order.go
> +	if err := rows.Err(); err != nil {
这个放在最前面

2022-07-25 02:41 UTC, flycash commented on internal/generate/testdata/order.go
> +	for rows.Next() {
要在每一个 Next 内部，创建 Order 的实例。你这种写法，其实大家都是共享一个 Order 变量，最终就会变成一个切片里面，所有的元素都是同一个

2022-07-25 02:41 UTC, flycash commented on internal/generate/testdata/user.go
> +	var val User
类似于这个 val，也应该在错误检测之后再初始化

2022-07-25 02:41 UTC, flycash commented on internal/generate/testdata/user.go
> +	var val User
在 Go 里面，作为中间件设计者，你要对任何引起内存分配的东西保持警惕，它会极大影响你的中间件性能

2022-07-26 08:22 UTC, jackj-ohn1 commented on internal/generate/testdata/order.go
> +	if err := rows.Err(); err != nil {
done

2022-07-26 08:22 UTC, jackj-ohn1 commented on internal/generate/testdata/order.go
> +	for rows.Next() {
done

2022-07-26 08:22 UTC, jackj-ohn1 commented on internal/generate/testdata/order.go
> +	var vals = make([]*Order, 0)
done

2022-07-26 08:22 UTC, jackj-ohn1 commented on internal/generate/testdata/user.go
> +	var val User
done

2022-07-26 12:31 UTC, flycash approved these changes

2022-07-26 12:31 UTC, merged