新增Update模板
gotomicro/egen pull request #7
Opened 2022-07-26 13:45 UTC by jackj-ohn1

2022-07-28 03:46 UTC, flycash requested changes
命名总体应该是 UpdateXXXByXXX。相当于说 Update XXX By XXX，这在英语里面还是稍微要通顺一点的。
然后这里面有一个笛卡尔积，从更新目标字段上来说：
- 更新全部字段
- 更新非零值字段
- 更新指定字段
从 WHERE 条件来说：
- 根据主键进行更新
- 根据 WHERE 条件进行更新

所以综合一下，应该有六个方法

2022-07-28 12:50 UTC, flycash requested changes

2022-07-28 12:50 UTC, flycash commented on internal/generate/mysql.go
> +		t := tMySQL.Lookup(v[15:])
为什么不接着使用之前的代码？这个15 看上去很令人迷惑

2022-07-28 12:50 UTC, flycash commented on internal/generate/mysql_template/update.gohtml
> +func (dao *{{.GoName}}DAO) QuotedNoneZero(val *{{.GoName}}) ([]interface{}, string) {
这个方法改成私有的方法，我们不希望别人拿到这个结果

2022-07-28 12:50 UTC, flycash commented on internal/generate/mysql_template/update.gohtml
> +    {{- if eq $control false}}
实际上，在这个步骤，应该是你直接拒绝生成代码了。也就是说，你可以在 modelInfo 生成的时候进行检测。不过这个可以后面来

2022-07-28 12:50 UTC, flycash commented on internal/generate/mysql_template/update.gohtml
> +func (dao *{{.GoName}}DAO) UpdatePrimaryKeyByWhere(ctx context.Context, val *{{.GoName}}, where string, args ...any) (int64, error) {
用 PK 来代表 PrimaryKey，PK 还算是比较常见的缩写

2022-07-28 12:50 UTC, flycash commented on internal/generate/mysql_template/update.gohtml
> +func (dao *{{.GoName}}DAO) UpdatePrimaryKeyByWhere(ctx context.Context, val *{{.GoName}}, where string, args ...any) (int64, error) {
而且这个不是更新主键，应该是 UpdateNonePKByWhere

2022-07-28 12:50 UTC, flycash commented on internal/generate/mysql_template/update.gohtml
> +func (dao *{{.GoName}}DAO) UpdateSpecificColByWhere(ctx context.Context, val *{{.GoName}}, where string, args ...any) (int64, error) {
直接命名为 UpdateColsByWhere 就可以了。
另外你这边其实可以看到，前面的 UpdateNonePKByWhere, UpdateNoneZero 其实都可以最终调用这个方法。这两个方法就是我们帮助用户将目标列筛选出来而已。所以前面的那些代码你都可以简化

2022-07-28 12:50 UTC, flycash commented on internal/generate/mysql_template/update.gohtml
> +    {{- if .Order}}
Order 代表的是什么？

2022-07-28 12:50 UTC, flycash commented on internal/generate/mysql_template/update.gohtml
> +    {{- if eq $control false}}
还有就是 if a == true 这种写法比较丑，到你这里，应该可以直接 if $control 吧？

2022-07-28 12:50 UTC, flycash commented on internal/generate/mysql_template/update.gohtml
> +    {{- if eq $control false}}
还有，你可以不用 control 变量的，因为你可以用 if-else 的语法，
if xxx
else if xxx
else if xxx
else 
   log.Fatal()
也就是你要在最后一个分支进行这个异常处理

2022-07-28 12:50 UTC, flycash commented on internal/generate/mysql_test.go
> +					{ColName: "login_time", GoName: "LoginTime", GoType: "string"},
从你的设计来看，你没有覆盖全部的情况，也就是说基本的类型你都没全部测试到。所有的 IsSlice 啥的都你都要全部测试到。也意味着你要在你的 User 或者 Order 里面加上对应的字段

2022-07-28 12:50 UTC, flycash commented on internal/generate/mysql_template/update.gohtml
> +    {{- if .IsMap}}
这里应该可以将这些判断是否为 nil 的，以及是否为 0 的分支进行合并吧？
比如说 if or .IsMap .IsPtr 这样
或者你进一步：
if .IsNilable
if .IsNumber

这样的话，分支数量能够减少很多

2022-07-28 12:53 UTC, jackj-ohn1 commented on internal/generate/mysql.go
> +		t := tMySQL.Lookup(v[15:])
之前那样的话 test的时候模板文件的顺序是随机的 生成的代码就和文件中的不一样

2022-07-28 12:54 UTC, jackj-ohn1 commented on internal/generate/mysql_template/update.gohtml
> +    {{- if eq $control false}}
搞忘了 一堆if好下饭

2022-07-28 12:55 UTC, jackj-ohn1 commented on internal/generate/mysql_template/update.gohtml
> +    {{- if .Order}}
用户指定的字段去update

2022-07-29 08:52 UTC, flycash commented on internal/generate/mysql.go
> +		t := tMySQL.Lookup(v[15:])
你可以定义一个总的 template，然后在这个 template 里面去引入别的 template。

2022-07-29 08:52 UTC, flycash commented on internal/generate/mysql.go
> +		t := tMySQL.Lookup(v[15:])
比如说你有一个 template:
```
{{ INSERT template}}
{{ update template}}
{{ select template}}
```

2022-07-29 08:56 UTC, flycash requested changes

2022-07-29 08:56 UTC, flycash commented on internal/generate/mysql_template/update.gohtml
> +    {{- else if .IsFloat}}
IsFloat 不可以和 IsInteger 合并吗？

2022-07-29 08:56 UTC, flycash commented on internal/generate/mysql_template/update.gohtml
> +    {{- else if not $control}}
{{ else }}

然后你就可以把 control 这个变量给删掉了

2022-07-29 08:56 UTC, flycash commented on internal/generate/mysql_template/update.gohtml
> +    {{- if .Order}}
哦哦哦，你误会了，应该是用户调用 UpdateColsByWhere(ctx, cols, where,  args...)

2022-07-29 08:56 UTC, flycash commented on internal/generate/mysql_template/update.gohtml
> +    {{- if .Order}}
你可以预期，用户每次更新都会不一样

2022-07-29 08:56 UTC, flycash commented on internal/generate/mysql_template/update.gohtml
> +    {{- if .Order}}
所以实际上 updateCols 要多一个指定的列的参数, cols []string

2022-07-29 09:15 UTC, jackj-ohn1 commented on internal/generate/mysql_template/update.gohtml
> +    {{- else if not $control}}
done

2022-07-29 09:17 UTC, jackj-ohn1 commented on internal/generate/mysql_template/update.gohtml
> +    {{- else if .IsFloat}}
done

2022-07-29 09:48 UTC, jackj-ohn1 commented on internal/generate/mysql.go
> +		t := tMySQL.Lookup(v[15:])
分了文件这样写的话会更麻烦把

2022-07-29 11:59 UTC, jackj-ohn1 commented on internal/generate/mysql.go
> +		t := tMySQL.Lookup(v[15:])
这种写法也没问题
files := []string{"insert.gohtml", "select.gohtml", "update.gohtml"}
	tMySQL := template.Must(template.ParseGlob("mysql_template/*.gohtml"))
	for _, v := range files {
		t := tMySQL.Lookup(v)
		err = t.Execute(writer, m)
		if err != nil {
			return err
		}
	}

2022-07-30 07:49 UTC, flycash requested changes
如果你打算 Update 和 Delete 一起提交，那么就改一下 PR 的标题

2022-07-30 07:49 UTC, flycash commented on internal/generate/testdata/order.go
> +func (dao *OrderDAO) DeleteColsByWhere(ctx context.Context, where string, args ...any) (int64, error) {
Delete 之类的就不需要 Cols 了，删除都是一整行全部删除，做不到只删除一行中的某些列

2022-07-30 07:49 UTC, flycash commented on internal/generate/testdata/order.go
> +func (dao *OrderDAO) quotedNonePK(val *Order) ([]interface{}, string) {
你这一整个方法，不是可以直接生成结果吗？
直接 return []string{val.OrderTime, val.OrderId} ... 
这样程序员都不用计算 append 了。

2022-07-30 07:49 UTC, flycash commented on internal/generate/mysql_template/update.gohtml
> +func (dao *{{.GoName}}DAO) UpdateColByRaw(ctx context.Context, query string, args ...any) (int64, error) {
要么你就都用 UpdateCol，要么就都用UpdateCols，保持一致就可以。

2022-07-30 07:49 UTC, flycash commented on internal/generate/mysql_test.go
> +					{ColName: "last_name", GoName: "LastName", Order: true, GoType: "string"},
所以 Order 这个字段可以删掉了吧

2022-07-30 08:01 UTC, flycash commented on internal/model/types.go
> +	}
直接合并为一个不就可以吗……

2022-07-30 08:06 UTC, jackj-ohn1 commented on internal/model/types.go
> +	}
感觉byte rune和别的不同 没int 就分开来感观更好点

2022-07-30 08:06 UTC, jackj-ohn1 commented on internal/generate/mysql_test.go
> +					{ColName: "last_name", GoName: "LastName", Order: true, GoType: "string"},
done

2022-07-30 08:15 UTC, flycash commented on internal/generate/mysql_template/update.gohtml
> +	return args, strings.Join(cols, "=?,")
```go
cols := []string{
{{- $idx, $ele := range .Fields}}
{{if gt $idx > 0}}
,
{{- end}}
$ele.ColName
{{- end}}
}
```

2022-07-30 10:11 UTC, flycash requested changes

2022-07-30 10:11 UTC, flycash commented on internal/generate/mysql.go
> +	tMySQL := template.Must(template.ParseGlob("mysql_template/*.gohtml"))
这样写会不会导致每一次生成的顺序都不一致？比如说最开始是 SELECT 在前，UPDATE 在后，但是第二次就变成了 UPDATE 在前，但是 SELECT 在后？

2022-07-30 10:11 UTC, flycash commented on internal/generate/mysql_template/delete.gohtml
> +func (dao *{{.GoName}}DAO) DeleteColsByWhere(ctx context.Context, where string, args ...any) (int64, error) {
DELETE 是不需要 DeleteCols 的

2022-07-30 10:11 UTC, flycash commented on internal/generate/mysql_test.go
> +					{ColName: "login_time", GoName: "LoginTime", GoType: "string"},
同样的，你这里依旧需要覆盖到全部的情况，IsPtr, IsMap, IsArray, IsSlice 这些

2022-08-01 10:47 UTC, flycash requested changes

2022-08-01 10:47 UTC, flycash commented on internal/generate/mysql_template/update.gohtml
> +    {{- else if or .IsPtr}}
你这里不需要 if or 吧？ 直接 if .IsSlice 或者 .IsPtr。
另外有一个，我思来想去，还是觉得 .IsSlice 也用 nil 来判断。也就是说，对于用户来讲，slice 有三个值：
- nil：这就是我们要忽略的
- empty slice：len(s) == 0 的这种，意思是用户希望显式地覆盖掉，只不过是用空的来覆盖掉
- 普通的：那就是覆盖

我觉得 nil 和 len(s) ==0 在语义上还是要区别出来。 nil 是用户没有赋值，len(s) 是用户赋值了，但是值恰好是空的切片

2022-08-01 10:47 UTC, flycash commented on internal/generate/mysql_test.go
> +					{ColName: "seller", GoName: "Seller", GoType: "ptr"},
GoType 这里不太行，应该是保持 `*int` 这个值。然后判断是不是指针，也就是判断前缀是不是 *

2022-08-01 10:47 UTC, flycash commented on internal/generate/mysql_test.go
> +					{ColName: "seller", GoName: "Seller", GoType: "ptr"},
我比较担忧我们后面判断是指针的时候，我们还希望进一步判断指针指向的具体类型是什么

2022-08-01 10:47 UTC, flycash commented on internal/generate/mysql_test.go
> +					{ColName: "password", GoName: "Password", GoType: "slice"},
类似于下面对指针的看法，这里 GoType 最好保持 `[]byte` 这种形态，这样你判断是不是 slice 就通过判断前缀是不是 [] 来判断

2022-08-02 13:19 UTC, flycash approved these changes

2022-08-02 13:19 UTC, merged